{% set name = "hdxrate" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c98918a594781f4793c3784c438172fe6d634545a1a8cf45077af287dd80897

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - hdxrate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Jhsmit/HDXrate
  summary: Calculate HDX intrinsic exchange rates.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jhsmit
