{% set name = "hdxrate" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/HDXrate-{{ version }}.tar.gz
  sha256: 17d4d460d1ccd6d33c55090f81230b96f6e61354e8348cddf57b6fb87397f86e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6

test:
  imports:
    - hdxrate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/HDXrate
  summary: Calculate HDX intrinsic exchange rates.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jhsmit
