{% set name = "hdxrate" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/HDXrate-{{ version }}.tar.gz
  sha256: a8da72e8a380ae9fdc5657865f39b03aedcfce6ff922eefb9c8c7c7b4aa2d6b1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - hdxrate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Jhsmit/HDXrate
  summary: Calculate HDX intrinsic exchange rates.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jhsmit
